### ISSUE TITLE
Containers, parameters, general to-do

### ISSUE THREAD

**Issue by alextidd** [Phuong-Le/process_sanger_lcm-nf#11]
Next steps:
- [ ] change hairpin process to run within singularity image (shub://MathijsSanders/SangerLCMFilteringSingularity)
- [ ] build singularity image for vcf_flag_modifier.py (python packages - pkg_resources, argparse, os, sys) (based on docker://quay.io/wtsicgp/vcf_flag_modifier)
- [ ] add parameter to set project_type (whole genome / whole exome)
- [ ] try to set default image to null for all processes and then specify containers for containerised processes afterwards (like in https://github.com/alextidd/chemo_trees/blob/main/nf-chemo-trees/nextflow.config)
- [ ] figure out why phuong branch is hidden
- [ ] set defaults for fragment length filtering: CLPM = 0, ASRD = 1 (can set 0.87), ASMD = 140 - create a parameter. If ASRD is passed, ASMD filter is skipped. ASRD always supercedes ASMD.
- [ ] parameterise all of the arguments 
- [ ] nf-schema for the parameters

Potential future steps:
- [ ] change from cgpVAF to bamtoR based method (ask Andrew and Pan), or parallelise cgpVAF by chromosome + batch up by patient (10 samples per job, same bed intervals per patient) (@alextidd)
- [ ] Add parameters to switch between clone tree and sample tree?
- [ ] conpair

**Comment by Phuong-Le** [comment]
[] conpair contamination filter for samples with no match normal 
[] indels 
[] add reflag before hairpin
