### ISSUE TITLE
Nextflow Hackathon Barcelona TO-DO

### ISSUE THREAD

**Issue by alextidd** [Phuong-Le/process_sanger_lcm-nf#16]
- [ ] Add and containerise hairpin2
- [ ] Fix the modules / workflows structure ({moduleName}/main.nf)
- [ ] Each command should be added to a separate module file (e.g. move vcfilter and tabix out of hairpin step)
- [ ] Rename all instances of snp -> snv
- [ ] Create test dataset and implement nf-test
- [ ] Start using igenomes
